[package]
name = "plist"
version = "1.0.1"
authors = ["Ed Barnard <eabarnard@gmail.com>"]
description = "A rusty plist parser. Supports Serde serialization."
license = "MIT"
repository = "https://github.com/ebarnard/rust-plist/"
documentation = "https://docs.rs/plist/1.0.1/plist/"
keywords = ["plist", "parser"]
categories = ["config", "encoding", "parser-implementations"]
edition = "2018"

[features]
default = ["serde"]
enable_unstable_features_that_may_break_with_minor_version_bumps = []

[dependencies]
base64 = "0.13"
chrono = { version = "0.4", default-features = false, features = ["std"] }
indexmap = "1.6"
line-wrap = "0.1.1"
xml-rs = "0.8"
serde = { version = "1.0", optional = true }

[dev-dependencies]
serde_derive = { version = "1.0" }
